server:
  port: 8080

spring:
  # NOTE:热部署出现的问题
#  devtools:
#    restart:
#      additional-exclude: com/example/psychroomserver/model/**

  application:
    name: PsychRoomServer
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/psychroom?useUnicode=true&characterEncoding=utf8
    username: pyh233
    password:
    hikari:
      connection-timeout: 3000
      maximum-pool-size: 50
      max-lifetime: 360000

#  web:
#    resources:
#      static-locations: file:/${custom.img.upload.location}
#  mvc:
#    static-path-pattern: /static/**
  data:
    redis:
      host: localhost
      port: 6379
      password:
      timeout: 300
      database: 0
  cache:
    type: redis
# 分布式session存储设置
#  session:
#    store-type=redis:mybatis:
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-prefix: mybatis.log.
    log-impl: org.apache.ibatis.logging.commons.JakartaCommonsLoggingImpl
    lazy-loading-enabled: false
    cache-enabled: true
  type-aliases-package: com.example.psychroomserver.model
  mapper-locations: classpath:/mapper/**/*.xml
jwt:
  secret:
    key: 123456
logging:
  level:
    mybatis:
      log: DEBUG
custom:
  img:
    upload:
      location: G:/NewJava/Projects/PsychRoomServer/src/main/resources/upload/

############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: sa-token
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 86400
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: 1800
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
#  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
#  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
#  token-style: uuid
  # 是否输出操作日志
  is-log: true
  # jwt秘钥
  jwt-secret-key: 123456
